In [1]:
import numpy as np

v = np.array([[5,2,1]])

v, v.shape

(array([[5, 2, 1]]), (1, 3))

In [2]:
v[0]

array([5, 2, 1])

In [3]:
v_transpose = np.transpose(v)

v_transpose, v_transpose.shape

(array([[5],
        [2],
        [1]]), (3, 1))

In [4]:
v_transpose[0]

array([5])

In [5]:
v[0][1]

2

In [6]:
v = np.array([[1,2,3],[2, 0, 1]])

print('v:', v)
print('v.shape:', v.shape)
print('v.size:', v.size)

v: [[1 2 3]
 [2 0 1]]
v.shape: (2, 3)
v.size: 6


In [7]:
v_transpose = np.transpose(v)
print('v_transpose:', v_transpose)
print('v_transpose.shape:', v_transpose.shape)
print('v_transpose.size:', v_transpose.size)

v_transpose: [[1 2]
 [2 0]
 [3 1]]
v_transpose.shape: (3, 2)
v_transpose.size: 6


In [8]:
v = np.array([[1,2,3],[2, 0, 1]])
print('v.reshape(3,2)\n', v.reshape(3,2))

# By applying the following reshape, we transform the matrix into 3D Tensor

print('v.reshape(3,1,2)\n', v.reshape(3,1,2))

# -1 specifies that we don't care about the dimension. Find highest dimension
# One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.
print('v.reshape(-1,1,2)\n', v.reshape(-1,1,2))

v.reshape(3,2)
 [[1 2]
 [3 2]
 [0 1]]
v.reshape(3,1,2)
 [[[1 2]]

 [[3 2]]

 [[0 1]]]
v.reshape(-1,1,2)
 [[[1 2]]

 [[3 2]]

 [[0 1]]]


In [9]:
v = np.array([[[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])

print(v)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]


In [10]:
# The first element of shape shows how many, and the second and third elements shows the dimension
print(v.shape)

(2, 2, 3)


In [11]:
print(v[0])

[[1. 2. 3.]
 [4. 5. 6.]]


In [12]:
print(v[1])

[[ 7.  8.  9.]
 [11. 12. 13.]]


In [13]:
print(v[2])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [14]:
print(v.size)

12


In [15]:
print(v.reshape(3,2,-1))

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 11.]
  [12. 13.]]]


In [16]:
print(v.reshape(3,-1,1))

[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]

 [[ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]

 [[ 9.]
  [11.]
  [12.]
  [13.]]]


In [17]:
v.reshape(1,1,12)

array([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11., 12., 13.]]])

In [18]:
# 4d tensor
v = np.zeros((2, 3, 5, 5))

print(v)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [19]:
# 5d tensor

v = np.zeros((2, 2, 3, 5, 5))
print(v)
print(v[0][0].shape)
print(v[0][1].shape)
print(v[1][0].shape)
print(v[1][1].shape)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 

In [20]:
a = np.array([[4, 2, 3],[2, 0, 1]])

b = np.transpose(a)

c = np.dot(a,b)

print(c)

[[29 11]
 [11  5]]


In [23]:
a = np.array([[4, 2, 3],[2, 0, 1]])

b = np.transpose(a)

np.dot(b, a)

array([[20,  8, 14],
       [ 8,  4,  6],
       [14,  6, 10]])

In [32]:
# Element wise multiplication

import numpy as np
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
print(np.multiply(a,b))
print(np.multiply(b,a))
print(a*b)
print(b*a)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [40]:
np.random.seed(42)

# Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])


#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

def relu(x):
    return np.maximum(0, x)

def relu_backward(x, )


# for i in range(epoch):
#     #Forward Propogation
#     hidden_layer_input1=np.dot(X,wh)
#     hidden_layer_input=hidden_layer_input1 + bh
#     hiddenlayer_activations = sigmoid(hidden_layer_input)
#     output_layer_input1=np.dot(hiddenlayer_activations,wout)
#     output_layer_input= output_layer_input1+ bout
#     output = sigmoid(output_layer_input)

#     #Backpropagation
#     D = y-output
#     slope_output_layer = derivatives_sigmoid(output)
#     slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
#     d_output = D * slope_output_layer
#     Error_at_hidden_layer = d_output.dot(wout.T)
#     d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
#     wout += hiddenlayer_activations.T.dot(d_output) *lr
#     bout += np.sum(d_output, axis=0,keepdims=True) *lr
#     wh += X.T.dot(d_hiddenlayer) *lr
#     bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
    
# print(output)


# try relu method
for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = relu(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = relu(output_layer_input)

    #Backpropagation
    D = y-output
    slope_output_layer = relu_backward(output)
    slope_hidden_layer = relu_backward(hiddenlayer_activations)
    d_output = D * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
    
print(output)


[[2.07631257]
 [2.72140538]
 [1.62885117]]
