In [8]:
import numpy as np

v = np.array([[5,2,1]])

v, v.shape

(array([[5, 2, 1]]), (1, 3))

In [13]:
v[0]

array([5, 2, 1])

In [11]:
v_transpose = np.transpose(v)

v_transpose, v_transpose.shape

(array([[5],
        [2],
        [1]]), (3, 1))

In [15]:
v_transpose[0]

array([5])

In [12]:
v[0][1]

2

In [17]:
v = np.array([[1,2,3],[2, 0, 1]])

print('v:', v)
print('v.shape:', v.shape)
print('v.size:', v.size)

v: [[1 2 3]
 [2 0 1]]
v.shape: (2, 3)
v.size: 6


In [18]:
v_transpose = np.transpose(v)
print('v_transpose:', v_transpose)
print('v_transpose.shape:', v_transpose.shape)
print('v_transpose.size:', v_transpose.size)

v_transpose: [[1 2]
 [2 0]
 [3 1]]
v_transpose.shape: (3, 2)
v_transpose.size: 6


In [24]:
v = np.array([[1,2,3],[2, 0, 1]])
print('v.reshape(3,2)\n', v.reshape(3,2))

# By applying the following reshape, we transform the matrix into 3D Tensor

print('v.reshape(3,1,2)\n', v.reshape(3,1,2))

# -1 specifies that we don't care about the dimension. Find highest dimension
# One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.
print('v.reshape(-1,1,2)\n', v.reshape(-1,1,2))

v.reshape(3,2)
 [[1 2]
 [3 2]
 [0 1]]
v.reshape(3,1,2)
 [[[1 2]]

 [[3 2]]

 [[0 1]]]
v.reshape(-1,1,2)
 [[[1 2]]

 [[3 2]]

 [[0 1]]]


In [26]:
v = np.array([[[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])

print(v)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]


In [27]:
# The first element of shape shows how many, and the second and third elements shows the dimension
print(v.shape)

(2, 2, 3)


In [28]:
print(v[0])

[[1. 2. 3.]
 [4. 5. 6.]]


In [29]:
print(v[1])

[[ 7.  8.  9.]
 [11. 12. 13.]]


In [30]:
print(v[2])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [31]:
print(v.size)

12


In [32]:
print(v.reshape(3,2,-1))

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 11.]
  [12. 13.]]]


In [33]:
print(v.reshape(3,-1,1))

[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]

 [[ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]

 [[ 9.]
  [11.]
  [12.]
  [13.]]]


In [41]:
v.reshape(1,1,12)

array([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11., 12., 13.]]])

In [42]:
# 4d tensor
v = np.zeros((2, 3, 5, 5))

print(v)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [43]:
# 5d tensor

v = np.zeros((2, 2, 3, 5, 5))
print(v)
print(v[0][0].shape)
print(v[0][1].shape)
print(v[1][0].shape)
print(v[1][1].shape)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 